emilio_website/apps/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('profile', views.ProfileView.as_view(), name='profile'),

    #Django Auth
    path('login',
         auth_views.LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('logout',
         auth_views.LogoutView.as_view(),
         name='logout')
]

emilio_website/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emilio_website.apps.public.urls')),
    path('accounts/', include('emilio_website.apps.accounts.urls')),]

emilio_website/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserInterest(models.Model):  # hobbies
    name = models.CharField(max_length=100, unique=True)
    normalized_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class UserPersona(models.Model):
    name = models.CharField(max_length=100, unique=True)
    normalized_name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    # owner
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name='profile')

    # settings
    is_full_name_displayed = models.BooleanField(default=True)

    # details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL,
                                blank=True, null=True, )
    interests = models.ManyToManyField(UserInterest, blank=True)

emilio_website/apps/accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

emilio_website/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
<h1>
    About
</h1>
{% endblock %}

emilio_website/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %} <!-- prevents hackers from accessing form -->
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

emilio_website/templates/accounts/profile.html
<!-- NOTE: this code is good for smaller user bases, but will need to be
refactored if thousands users enter site due to how data is being accessed-->

{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}
<h1>
    {{user.get_full_name}} (@{{user.username}})
</h1>

{% with profile=user.profile %}
    {% if profile %}
    <h2>
        {{ profile.persona|default:"" }}
        <!-- MUST pass a default or will show up as 'None' -->
    </h2>
    <div>
        {{ profile.bio|default:"" }}
    </div>
    <div>
        {% with website=profile.website|default:"" %}
            <a href="{{website}}">{{website}}</a>
        {% endwith %}
    </div>
    <br/>
    <div>
        Interests:
        {% for interest in profile.interests.all %} <!-- a query -->
            <span>
                {{ interest.name }}{% if not forloop.last %},
                {% endif %}
            </span>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}


{% endblock %}

emilio_website/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Flower Shop{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'theme/css/styles.css' %}" rel="stylesheet" />
        <!-- Custom theme-->
        <link href="{% static 'css/main.css' %}" rel="stylesheet" />
</head>
<body>
    <!-- Navbar -->
    {% include 'navbar.html' %}

    <!-- Main -->
    <main id="main">
        {% block content %}
        {% endblock %}
    </main>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'theme/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

emilio_website/templates/contact.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>
    Contact
</h1>
{% endblock %}

emilio_website/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}

<h1>
    Mowpage
</h1>
{% endblock %}

emilio_website/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#page-top">Emilio.com</a>
                <button class="navbar-toggler text-uppercase font-weight-bold hs-bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        {% url 'public:index' as index_url %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">Dashboard</a></li>
                        {% url 'public:about' as about_url %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if request.path == about_url %}active{% endif %}" href="{{ about_url }}">About</a></li>
                        {% url 'public:contact' as contact_url %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded{% if request.path == contact_url %}active{% endif %}" href="{{ contact_url }}">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
<!-- <nav>
<div>
    {% url 'public:index' as index_url %}
    <span>{% if request.path == index_url %}Home{% else %}
        <a href="{{index_url}}">Home</a>{% endif %}</span>

    {% url 'public:about' as about_url %}
    <span>{% if request.path == about_url %}About{% else %}
        <a href="{{about_url}}">About</a>{% endif %}</span>

    {% url 'public:contact' as contact_url %}
    <span>{% if request.path == contact_url %}Contact{% else %}
        <a href="{{contact_url}}">Contact</a>{% endif %}</span>

    <span style="float:right">
        {% if user.is_authenticated %}
            {% url 'accounts:profile' as profile_url %}
            <span>Hi {% if request.path == profile_url %}{{user.username}}
                {% else %}<a href="{{profile_url}}">{{user.username}}</a>
                {% endif %}</span>

            It seems that the GET action for logout was deprecated,
            had to create a form instead
            {% url 'accounts:logout' as logout_url %}
            <form method="post" action="{{logout_url}}">
                {% csrf_token %}
                <button type="submit">logout</button>
            </form>
        {% else %}
            {% url 'accounts:login' as login_url %}
            <span><a href="{{login_url}}">Login</a></span>
        {% endif %}
    </span>
</div>
</nav>-->